export const icons = {
  arrowUp: '􀆇',
  arrowDown: '􀆈',
  arrowRight: '􀆊',
  arrowLeft: '􀯶',
  hamburger: '􀌇',
  talk: '􀌤',
  heart: '􀊴',
  heartFill: '􀊵',
  plus: '􀅼',
  home: '􀎞',
  list: '􀤦',
  person: '􀉩',
  close: '􀆄',
  search: '􀊫',
  camera: '􀌞',
  keyboard: '􀓖',
  filter: '􀌆',
  more: '􀍠',
};
