FROM node:18 AS build

WORKDIR /secondhand_web

COPY package*.json ./
RUN apt-get update && apt-get upgrade -y
RUN npm install

COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
