disabled_rules:
- line_length
- trailing_whitespace
- file_length

opt_in_rules:
- force_unwrapping
- function_body_length

excluded:
- Pods
- SecondHand/Detail/DetailContentView+layoutConstraint.swift

force_unwrapping:
  severity: error
  
function_body_length:
  - 25 # warning
  - 40 # error
