disabled_rules:
- line_length
- trailing_whitespace
- file_length
- void_return
- nesting
- function_body_length

opt_in_rules:
- force_unwrapping

excluded:
- Pods

force_unwrapping:
  severity: error
  
function_body_length:
  - 25 # warning
  - 40 # error
