# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SecondHand' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Toaster'
  pod 'SwiftLint'

  target 'SecondHandTests' do
    # Pods for testing
  end

  target 'SecondHandUITests' do
    # Pods for testing
  end

end
